# Generated by Django 5.1.6 on 2025-02-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_pro", models.CharField(blank=True, max_length=255, null=True)),
                ("wilaya", models.CharField(blank=True, max_length=255, null=True)),
                ("domaine", models.CharField(blank=True, max_length=255, null=True)),
                ("activity", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "validation_proposition",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "code_pro_processed",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "code_pro_language",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "wilaya_processed",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "wilaya_language",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "domaine_processed",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "domaine_language",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "activity_processed",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "activity_language",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("description_processed", models.TextField(blank=True, null=True)),
                (
                    "description_language",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "status_de_la_proposition",
                    models.CharField(
                        blank=True,
                        help_text="Leave empty if accepted, otherwise specify if redundant or forbidden.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("raison_du_choix_du_status", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
